### PR TITLE
Support Rails 7.1

### PR DESCRIPTION
**Pull request by olivier-thatch**
Add support for Rails 7.1.

### CODE REVIEW

**Comment by olivier-thatch** [comment]
Hm, it looks like the salsify/ruby_ci Docker image no longer exists. I don't have experience with CircleCI either. Would you consider moving CI to Github Actions? If so I can take a stab at setting it up.

**Review by jturkel — CHANGES_REQUESTED** [review]
Thanks for getting this started. I've opened #55 to fix the CircleCI build for this project. Other than getting the build passing there are a few more changes required:

- Updating the rails version constraints in `safer_rails_console.gemspec`
- Adding a new entry for Rails 7.1 in `Appraisals` and checking in the generated `gemfiles/7.1.gemfile`
- Bumping the version number in `lib/safer_rails_console/version.rb`
- Adding a CHANGELOG entry

See https://github.com/salsify/safer_rails_console/pull/35 for an example of a previous Rails upgrade.

**Comment by olivier-thatch** [comment]
Oh oops, I actually did all that but goofed up the commit. Will fix and update. Thanks for fixing CI!

**Comment by olivier-thatch** [comment]
Alright, CI is passing now.

The only notable change for Rails 7.1 is that Rails now requires the [`secret_key_base`](https://api.rubyonrails.org/classes/Rails/Application.html#method-i-secret_key_base) to be set when Active Record is loaded in production (I believe due to [this feature](https://edgeguides.rubyonrails.org/7_1_release_notes.html#add-activerecord-base-generates-token-for), which causes `secret_key_base` to be accessed in [this railtie](https://github.com/rails/rails/blob/v7.1.0/activerecord/lib/active_record/railtie.rb#L371-L377)).

Since the actual key does not matter here, I've simply set the `SECRET_KEY_BASE_DUMMY` environment variable to `1`. This is also a new Rails 7.1 [feature](https://hayford.dev/this-week-in-rails-wrapped-an-overview-of-rails-7-1-features-part-iii/#12-assetsprecompile-to-run-in-a-production-build-step-without-passing-in-rails_master_key) which simply generates a temporary key on the fly. It has no effect on previous Rails versions. Let me know what you think.

**Review by jturkel — APPROVED** [review]
Thanks for the contribution!

**Comment by olivier-thatch** [comment]
👍  Thanks for the release! :)

**Pull request merged**
